# Generated by Django 3.2.7 on 2022-02-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pentaword', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word_reference',
        ),
    ]
